In [1]:
import pandas as pd
import re

charts = pd.read_csv(
    "spotify_charts.csv",
    usecols=["title", "artist", "url"],
    nrows=20
)

def extract_track_id(url):
    match = re.search(r"track/([A-Za-z0-9]+)", str(url))
    return match.group(1) if match else None

charts["track_id"] = charts["url"].apply(extract_track_id)
charts.head(10)

,title,artist,url,track_id
0,Chantaje (feat. Maluma),Shakira,https://open.spotify.com/track/6mICuAdrwEjh6Y6...,6mICuAdrwEjh6Y6lroV2Kg
1,Vente Pa' Ca (feat. Maluma),Ricky Martin,https://open.spotify.com/track/7DM4BPaS7uofFul...,7DM4BPaS7uofFul3ywMe46
2,Reggaetón Lento (Bailemos),CNCO,https://open.spotify.com/track/3AEZUABDXNtecAO...,3AEZUABDXNtecAOSC1qTfo
3,Safari,"J Balvin, Pharrell Williams, BIA, Sky",https://open.spotify.com/track/6rQSrBHf7HlZjtc...,6rQSrBHf7HlZjtcMZ4S4bO
4,Shaky Shaky,Daddy Yankee,https://open.spotify.com/track/58IL315gMSTD37D...,58IL315gMSTD37DOZPJ2hf
5,Traicionera,Sebastian Yatra,https://open.spotify.com/track/5J1c3M4EldCfNxX...,5J1c3M4EldCfNxXwrwt8mT
6,Cuando Se Pone a Bailar,Rombai,https://open.spotify.com/track/1MpKZi1zTXpERKw...,1MpKZi1zTXpERKwxmOu1PH
7,Otra vez (feat. J Balvin),Zion & Lennox,https://open.spotify.com/track/3QwBODjSEzelZyV...,3QwBODjSEzelZyVjxPOHdq
8,La Bicicleta,"Carlos Vives, Shakira",https://open.spotify.com/track/0sXvAOmXgjR2QUq...,0sXvAOmXgjR2QUqLK1MltU
9,Dile Que Tu Me Quieres,Ozuna,https://open.spotify.com/track/20ZAJdsKB5IGbGj...,20ZAJdsKB5IGbGj4ilRt2o

In [2]:
songs = pd.read_csv(
    "spotify_songs.csv",
    usecols=["track_id", "track_name", "track_artist"]
)

test_merge = charts.merge(songs, on="track_id", how="left")
test_merge[["title", "artist", "track_id", "track_name", "track_artist"]].head(10)

,title,artist,track_id,track_name,track_artist
0,Chantaje (feat. Maluma),Shakira,6mICuAdrwEjh6Y6lroV2Kg,Chantaje (feat. Maluma),Shakira
1,Vente Pa' Ca (feat. Maluma),Ricky Martin,7DM4BPaS7uofFul3ywMe46,Vente Pa' Ca,Ricky Martin
2,Vente Pa' Ca (feat. Maluma),Ricky Martin,7DM4BPaS7uofFul3ywMe46,Vente Pa' Ca,Ricky Martin
3,Reggaetón Lento (Bailemos),CNCO,3AEZUABDXNtecAOSC1qTfo,Reggaetón Lento (Bailemos),CNCO
4,Reggaetón Lento (Bailemos),CNCO,3AEZUABDXNtecAOSC1qTfo,Reggaetón Lento (Bailemos),CNCO
5,Safari,"J Balvin, Pharrell Williams, BIA, Sky",6rQSrBHf7HlZjtcMZ4S4bO,Safari,J Balvin
6,Safari,"J Balvin, Pharrell Williams, BIA, Sky",6rQSrBHf7HlZjtcMZ4S4bO,Safari,J Balvin
7,Shaky Shaky,Daddy Yankee,58IL315gMSTD37DOZPJ2hf,NaN,NaN
8,Traicionera,Sebastian Yatra,5J1c3M4EldCfNxXwrwt8mT,Traicionera,Sebastian Yatra
9,Cuando Se Pone a Bailar,Rombai,1MpKZi1zTXpERKwxmOu1PH,NaN,NaN